# Header
menu:
  Home: /
  Upcoming events: /upcoming/
menuFooter:
  Home: /
  Upcoming events: /upcoming/
  News archive: /archives/
  Privacy policy: /privacy/
rss: /rss.xml
excerpt_link: Read More
widgets:
- upcoming
- recent_posts
- feedback
widgetsFooter:
- upcoming
- recent_posts
widgetsHome:
- twitter
favicon: /images/logo/logo-512.png
logoSvg: /images/logo/logo.svg
